qcow2_include = include_directories('.')

qcow2_sources = [
  'qcow2.c',
  'qcow2-refcount.c',
  'qcow2-cache.c',
  'qcow2-cluster.c',
  'qcow2-bitmap.c',
  'qcow2-threads.c',
  'qcow2-snapshot.c',
  'authz/base.c',
  'block.c',
  'blockdev.c',
  'blockjob.c',
  'block/accounting.c',
  'block/aio_task.c',
  'block/block-backend.c',
  'block/block-gen.c',
  'block/commit.c',
  'block/dirty-bitmap.c',
  'block/file-posix.c',
  'block/graph-lock.c',
  'block/io.c',
  'block/linux-aio.c',
  'block/mirror.c',
  'block/monitor/bitmap-qmp-cmds.c',
  'block/progress_meter.c',
  'block/qapi.c',
  'block/raw-format.c',
  'block/snapshot.c',
  'hw/block/block.c',
  'hw/block/hd-geometry.c',
  'io/channel.c',
  'io/channel-file.c',
  'io/channel-socket.c',
  'io/channel-util.c',
  'io/channel-watch.c',
  'io/task.c',
  'job.c',
  'job-qmp.c',
  'qapi/qapi-clone-visitor.c',
  'qapi/qapi-dealloc-visitor.c',
  'qapi/qapi-events-block-core.c',
  'qapi/qapi-events-job.c',
  'qapi/qapi-types-block-core.c',
  'qapi/qapi-types-crypto.c',
  'qapi/qapi-types-common.c',
  'qapi/qapi-types-job.c',
  'qapi/qapi-types-sockets.c',
  'qapi/qapi-types-yank.c',
  'qapi/qapi-util.c',
  'qapi/qapi-visit-block-core.c',
  'qapi/qapi-visit-common.c',
  'qapi/qapi-visit-crypto.c',
  'qapi/qapi-visit-core.c',
  'qapi/qapi-visit-job.c',
  'qapi/qapi-visit-sockets.c',
  'qapi/qapi-visit-yank.c',
  'qapi/qmp-dispatch.c',
  'qapi/qmp-event.c',
  'qapi/qobject-input-visitor.c',
  'qapi/qobject-output-visitor.c',
  'qapi/string-input-visitor.c',
  'qapi/string-output-visitor.c',
  'qobject/block-qdict.c',
  'qobject/json-lexer.c',
  'qobject/json-parser.c',
  'qobject/json-streamer.c',
  'qobject/json-writer.c',
  'qobject/qbool.c',
  'qobject/qdict.c',
  'qobject/qjson.c',
  'qobject/qlist.c',
  'qobject/qnull.c',
  'qobject/qnum.c',
  'qobject/qobject.c',
  'qobject/qstring.c',
  'qom/object.c',
  'qom/container.c',
  'qom/qom-qobject.c',
  'system/cpus.c',
  'util/aio-posix.c',
  'util/aio-wait.c',
  'util/aiocb.c',
  'util/async.c',
  'util/bitmap.c',
  'util/bitops.c',
  'util/bufferiszero.c',
  'util/compatfd.c',
  'util/coroutine-ucontext.c',
  'util/cutils.c',
  'util/defer-call.c',
  'util/error.c',
  'util/error-report.c',
  'util/event_notifier-posix.c',
  'util/fdmon-epoll.c',
  'util/fdmon-poll.c',
  'util/hbitmap.c',
  'util/host-utils.c',
  'util/id.c',
  'util/iov.c',
  'util/lockcnt.c',
  'util/main-loop.c',
  'util/memalign.c',
  'util/module.c',
  'util/notify.c',
  'util/osdep.c',
  'util/oslib-posix.c',
  'util/qemu-config.c',
  'util/qemu-coroutine.c',
  'util/qemu-coroutine-lock.c',
  'util/qemu-option.c',
  'util/qemu-print.c',
  'util/qemu-sockets.c',
  'util/qemu-thread-posix.c',
  'util/qemu-timer-common.c',
  'util/qemu-timer.c',
  'util/qsp.c',
  'util/range.c',
  'util/rcu.c',
  'util/stats64.c',
  'util/thread-pool.c',
  'util/timed-average.c',
  'util/transactions.c',
  'util/unicode.c',
  'util/uri.c',
  'util/yank.c',
  ]

compiler = meson.get_compiler('c')
aio_dep = compiler.find_library('aio')
dl_dep = compiler.find_library('dl')
pthread_dep = dependency('threads')
glib_dep = dependency('glib-2.0')
zlib_dep = dependency('zlib')
zstd_dep = dependency('libzstd')

qcow2_libs = both_libraries('qcow2',
  qcow2_sources,
  include_directories : [
    incdir,
    lvm_incdir,
    qcow2_include,
  ],
  dependencies : [
    aio_dep,
    dl_dep,
    pthread_dep,
    uuid_dep,
    glib_dep,
    zlib_dep,
    zstd_dep,
  ],
  link_with : lvmutil_slib,
  version : '1.1.1',
  c_args : [
    '-D_GNU_SOURCE',
  ],
  install : true,
  # Vendored QEMU sources: don't enforce this project's -Werror on them.
  override_options : [
    'werror=false',
  ],
)
