/* qcow2/lib/system/cpus.c */
#define trace_vm_stop_flush_all(...)  do {} while(0)
/* qcow2/lib/hw/block/hd-geometry.c */
#define trace_hd_geometry_lchs_guess(...)  do {} while(0)
#define trace_hd_geometry_guess(...)  do {} while(0)
/* qcow2/lib/qapi/qapi-visit-core.c */
#define trace_visit_complete(...)  do {} while(0)
#define trace_visit_free(...)  do {} while(0)
#define trace_visit_start_struct(...)  do {} while(0)
#define trace_visit_check_struct(...)  do {} while(0)
#define trace_visit_end_struct(...)  do {} while(0)
#define trace_visit_start_list(...)  do {} while(0)
#define trace_visit_next_list(...)  do {} while(0)
#define trace_visit_check_list(...)  do {} while(0)
#define trace_visit_end_list(...)  do {} while(0)
#define trace_visit_start_alternate(...)  do {} while(0)
#define trace_visit_end_alternate(...)  do {} while(0)
#define trace_visit_optional(...)  do {} while(0)
#define trace_visit_policy_reject(...)  do {} while(0)
#define trace_visit_policy_skip(...)  do {} while(0)
#define trace_visit_type_int(...)  do {} while(0)
#define trace_visit_type_uint8(...)  do {} while(0)
#define trace_visit_type_uint16(...)  do {} while(0)
#define trace_visit_type_uint32(...)  do {} while(0)
#define trace_visit_type_uint64(...)  do {} while(0)
#define trace_visit_type_int8(...)  do {} while(0)
#define trace_visit_type_int16(...)  do {} while(0)
#define trace_visit_type_int32(...)  do {} while(0)
#define trace_visit_type_int64(...)  do {} while(0)
#define trace_visit_type_size(...)  do {} while(0)
#define trace_visit_type_bool(...)  do {} while(0)
#define trace_visit_type_str(...)  do {} while(0)
#define trace_visit_type_number(...)  do {} while(0)
#define trace_visit_type_any(...)  do {} while(0)
#define trace_visit_type_null(...)  do {} while(0)
#define trace_visit_type_enum(...)  do {} while(0)
/* qcow2/lib/io/channel-file.c */
#define trace_qio_channel_file_new_fd(...)  do {} while(0)
#define trace_qio_channel_file_new_path(...)  do {} while(0)
/* qcow2/lib/io/channel-socket.c */
#define trace_qio_channel_socket_new(...)  do {} while(0)
#define trace_qio_channel_socket_new_fd(...)  do {} while(0)
#define trace_qio_channel_socket_connect_sync(...)  do {} while(0)
#define trace_qio_channel_socket_connect_fail(...)  do {} while(0)
#define trace_qio_channel_socket_connect_complete(...)  do {} while(0)
#define trace_qio_channel_socket_connect_async(...)  do {} while(0)
#define trace_qio_channel_socket_listen_sync(...)  do {} while(0)
#define trace_qio_channel_socket_listen_fail(...)  do {} while(0)
#define trace_qio_channel_socket_listen_complete(...)  do {} while(0)
#define trace_qio_channel_socket_listen_async(...)  do {} while(0)
#define trace_qio_channel_socket_dgram_sync(...)  do {} while(0)
#define trace_qio_channel_socket_dgram_fail(...)  do {} while(0)
#define trace_qio_channel_socket_dgram_complete(...)  do {} while(0)
#define trace_qio_channel_socket_dgram_async(...)  do {} while(0)
#define trace_qio_channel_socket_accept(...)  do {} while(0)
#define trace_qio_channel_socket_accept_fail(...)  do {} while(0)
#define trace_qio_channel_socket_accept_complete(...)  do {} while(0)
/* qcow2/lib/io/task.c */
#define trace_qio_task_new(...)  do {} while(0)
#define trace_qio_task_thread_result(...)  do {} while(0)
#define trace_qio_task_thread_run(...)  do {} while(0)
#define trace_qio_task_thread_exit(...)  do {} while(0)
#define trace_qio_task_thread_source_attach(...)  do {} while(0)
#define trace_qio_task_thread_start(...)  do {} while(0)
#define trace_qio_task_thread_source_cancel(...)  do {} while(0)
#define trace_qio_task_complete(...)  do {} while(0)
/* qcow2/lib/util/aio-posix.c */
#define trace_poll_add(...)  do {} while(0)
#define trace_poll_remove(...)  do {} while(0)
#define trace_run_poll_handlers_begin(...)  do {} while(0)
#define trace_run_poll_handlers_end(...)  do {} while(0)
#define trace_poll_shrink(...)  do {} while(0)
#define trace_poll_grow(...)  do {} while(0)
/* qcow2/lib/util/async.c */
#define trace_reentrant_aio(...)  do {} while(0)
#define trace_aio_co_schedule_bh_cb(...)  do {} while(0)
#define trace_aio_co_schedule(...)  do {} while(0)
/* qcow2/lib/util/hbitmap.c */
#define trace_hbitmap_iter_skip_words(...)  do {} while(0)
#define trace_hbitmap_set(...)  do {} while(0)
#define trace_hbitmap_reset(...)  do {} while(0)
/* qcow2/lib/util/lockcnt.c */
#define trace_lockcnt_fast_path_attempt(...)  do {} while(0)
#define trace_lockcnt_fast_path_success(...)  do {} while(0)
#define trace_lockcnt_futex_wait_prepare(...)  do {} while(0)
#define trace_lockcnt_futex_wait(...)  do {} while(0)
#define trace_lockcnt_futex_wait_resume(...)  do {} while(0)
#define trace_lockcnt_futex_wake(...)  do {} while(0)
#define trace_lockcnt_unlock_attempt(...)  do {} while(0)
#define trace_lockcnt_unlock_success(...)  do {} while(0)
/* qcow2/lib/util/memalign.c */
#define trace_qemu_memalign(...)  do {} while(0)
#define trace_qemu_vfree(...)  do {} while(0)
/* qcow2/lib/util/module.c */
#define trace_module_load_module(...)  do {} while(0)
#define trace_module_lookup_object_type(...)  do {} while(0)
/* qcow2/lib/util/oslib-posix.c */
#define trace_qemu_anon_ram_alloc(...)  do {} while(0)
#define trace_qemu_anon_ram_free(...)  do {} while(0)
/* qcow2/lib/util/qemu-coroutine-lock.c */
#define trace_qemu_co_mutex_lock_entry(...)  do {} while(0)
#define trace_qemu_co_mutex_lock_return(...)  do {} while(0)
#define trace_qemu_co_mutex_lock_uncontended(...)  do {} while(0)
#define trace_qemu_co_mutex_unlock_entry(...)  do {} while(0)
#define trace_qemu_co_mutex_unlock_return(...)  do {} while(0)
/* qcow2/lib/util/qemu-coroutine.c */
#define trace_qemu_aio_coroutine_enter(...)  do {} while(0)
#define trace_qemu_coroutine_terminate(...)  do {} while(0)
#define trace_qemu_coroutine_yield(...)  do {} while(0)
/* qcow2/lib/util/qemu-sockets.c */
#define trace_socket_listen(...)  do {} while(0)
/* qcow2/lib/util/qemu-thread-common.h */
#define trace_qemu_mutex_lock(...)  do {} while(0)
#define trace_qemu_mutex_locked(...)  do {} while(0)
#define trace_qemu_mutex_unlock(...)  do {} while(0)
/* qcow2/lib/util/thread-pool.c */
#define trace_thread_pool_complete(...)  do {} while(0)
#define trace_thread_pool_cancel(...)  do {} while(0)
#define trace_thread_pool_submit(...)  do {} while(0)
/* qcow2/lib/authz/base.c */
#define trace_qauthz_is_allowed(...)  do {} while(0)
/* qcow2/lib/block/block-backend.c */
#define trace_blk_root_attach(...)  do {} while(0)
#define trace_blk_root_detach(...)  do {} while(0)
#define trace_blk_co_preadv(...)  do {} while(0)
#define trace_blk_co_pwritev(...)  do {} while(0)
/* qcow2/lib/block/commit.c */
#define trace_commit_one_iteration(...)  do {} while(0)
#define trace_commit_start(...)  do {} while(0)
/* qcow2/lib/block/dirty-bitmap.c */
/* qcow2/lib/block/file-posix.c */
#define trace_file_flush_fdatasync_failed(...)  do {} while(0)
#define trace_file_copy_file_range(...)  do {} while(0)
#define trace_zbd_zone_append_complete(...)  do {} while(0)
#define trace_zbd_zone_report(...)  do {} while(0)
#define trace_zbd_zone_mgmt(...)  do {} while(0)
#define trace_zbd_zone_append(...)  do {} while(0)
#define trace_file_FindEjectableOpticalMedia(...)  do {} while(0)
#define trace_file_setup_cdrom(...)  do {} while(0)
#define trace_file_hdev_is_sg(...)  do {} while(0)
/* qcow2/lib/block/io.c */
#define trace_bdrv_co_do_copy_on_readv(...)  do {} while(0)
#define trace_bdrv_co_preadv_part(...)  do {} while(0)
#define trace_bdrv_co_pwritev_part(...)  do {} while(0)
#define trace_bdrv_co_pwrite_zeroes(...)  do {} while(0)
#define trace_bdrv_co_copy_range_from(...)  do {} while(0)
#define trace_bdrv_co_copy_range_to(...)  do {} while(0)
/* qcow2/lib/block/mirror.c */
#define trace_mirror_iteration_done(...)  do {} while(0)
#define trace_mirror_yield_in_flight(...)  do {} while(0)
#define trace_mirror_one_iteration(...)  do {} while(0)
#define trace_mirror_restart_iter(...)  do {} while(0)
#define trace_mirror_yield(...)  do {} while(0)
#define trace_mirror_before_flush(...)  do {} while(0)
#define trace_mirror_before_drain(...)  do {} while(0)
#define trace_mirror_before_sleep(...)  do {} while(0)
#define trace_mirror_start(...)  do {} while(0)
/* qcow2/lib/qom/object.c */
#define trace_object_dynamic_cast_assert(...)  do {} while(0)
#define trace_object_class_dynamic_cast_assert(...)  do {} while(0)
/* qcow2/lib/qcow2-cache.c */
#define trace_qcow2_cache_entry_flush(...)  do {} while(0)
#define trace_qcow2_cache_flush(...)  do {} while(0)
#define trace_qcow2_cache_get(...)  do {} while(0)
#define trace_qcow2_cache_get_done(...)  do {} while(0)
#define trace_qcow2_cache_get_read(...)  do {} while(0)
#define trace_qcow2_cache_get_replace_entry(...)  do {} while(0)
/* qcow2/lib/qcow2-cluster.c */
#define trace_qcow2_l2_allocate(...)  do {} while(0)
#define trace_qcow2_l2_allocate_get_empty(...)  do {} while(0)
#define trace_qcow2_l2_allocate_write_l2(...)  do {} while(0)
#define trace_qcow2_l2_allocate_write_l1(...)  do {} while(0)
#define trace_qcow2_l2_allocate_done(...)  do {} while(0)
#define trace_qcow2_cluster_link_l2(...)  do {} while(0)
#define trace_qcow2_handle_copied(...)  do {} while(0)
#define trace_qcow2_do_alloc_clusters_offset(...)  do {} while(0)
#define trace_qcow2_cluster_alloc_phys(...)  do {} while(0)
#define trace_qcow2_handle_alloc(...)  do {} while(0)
#define trace_qcow2_alloc_clusters_offset(...)  do {} while(0)
/* qcow2/lib/qcow2-refcount.c */
#define trace_qcow2_process_discards_failed_region(...)  do {} while(0)
/* qcow2/lib/qcow2.c */
#define trace_qcow2_add_task(...) do {} while(0)
#define trace_qcow2_skip_cow(...) do {} while(0)
#define trace_qcow2_writev_data(...) do {} while(0)
#define trace_qcow2_writev_start_req(...) do {} while(0)
#define trace_qcow2_writev_start_part(...) do {} while(0)
#define trace_qcow2_writev_done_part(...) do {} while(0)
#define trace_qcow2_writev_done_req(...) do {} while(0)
#define trace_qcow2_pwrite_zeroes_start_req(...) do {} while(0)
#define trace_qcow2_pwrite_zeroes(...) do {} while(0)
